name: quiet_study
description: "Um aplicativo para encontrar e registrar locais de estudo silenciosos."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_markdown: ^0.7.1
  dots_indicator: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  geolocator: ^12.0.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/policies/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png" # Coloque seu ícone 1024x1024 aqui
  web:
    generate: true
  windows:
    generate: true